"""
recipes_data.py — All recipe data for CookMate.
To add more recipes, just copy the format below and add to the list!
"""

RECIPES = [
    {
        "id": 1,
        "name": "Pasta Carbonara",
        "country": "Italy",
        "category": "Meal",
        "ingredients": ["pasta", "eggs", "guanciale", "parmesan", "black pepper"],
        "time_minutes": 20,
        "cost_chf": 4.5,
        "calories": 650,
        "protein": 28,
        "carbs": 75,
        "fat": 22,
        "vegetarian": False,
        "vegan": False,
        "gluten_free": False,
        "dairy_free": False,
        "difficulty": "Easy",
        "description": "A classic Roman pasta dish — creamy, rich, and incredibly satisfying.",
        "lat": 41.9,
        "lon": 12.5,
        "steps": [
            "Boil pasta in salted water until al dente.",
            "Fry guanciale in a pan until crispy.",
            "Whisk eggs and grated parmesan together in a bowl.",
            "Drain pasta and add to the pan with pancetta (heat OFF).",
            "Pour egg mixture over pasta and toss quickly so it becomes creamy.",
            "Season with black pepper and serve immediately."
        ]
    },
    {
        "id": 2,
        "name": "Pad Thai",
        "country": "Thailand",
        "category": "Meal",
        "ingredients": ["rice noodles", "tofu", "eggs", "bean sprouts", "peanuts", "lime", "soy sauce"],
        "time_minutes": 25,
        "cost_chf": 5.0,
        "calories": 520,
        "protein": 22,
        "carbs": 68,
        "fat": 18,
        "vegetarian": True,
        "vegan": False,
        "gluten_free": True,
        "dairy_free": True,
        "difficulty": "Medium",
        "description": "Thailand's beloved stir-fried noodle dish — sweet, sour, and nutty.",
        "lat": 15.9,
        "lon": 100.9,
        "steps": [
            "Soak rice noodles in warm water for 20 min, then drain.",
            "Scramble eggs in a hot wok and set aside.",
            "Stir-fry tofu until golden.",
            "Add noodles and soy sauce; toss everything together.",
            "Add eggs back, then bean sprouts and peanuts.",
            "Squeeze lime on top and serve."
        ]
    },
    {
        "id": 3,
        "name": "Black Bean Tacos",
        "country": "Mexico",
        "category": "Meal",
        "ingredients": ["tortillas", "black beans", "avocado", "tomato", "lime", "coriander", "cheese"],
        "time_minutes": 15,
        "cost_chf": 3.5,
        "calories": 420,
        "protein": 18,
        "carbs": 55,
        "fat": 14,
        "vegetarian": True,
        "vegan": False,
        "gluten_free": False,
        "dairy_free": False,
        "difficulty": "Easy",
        "description": "Quick, cheap, and delicious — a student staple with a Mexican twist.",
        "lat": 23.6,
        "lon": -102.5,
        "steps": [
            "Warm beans in a pan with salt and cumin.",
            "Mash avocado with lime juice and salt.",
            "Warm tortillas in a dry pan for 30 seconds each.",
            "Fill tortillas with beans, avocado, tomato, and cheese.",
            "Top with coriander and a squeeze of lime."
        ]
    },
    {
        "id": 4,
        "name": "Chicken Curry",
        "country": "India",
        "category": "Meal",
        "ingredients": ["chicken", "onion", "tomatoes", "garlic", "ginger", "curry powder", "rice", "coconut milk"],
        "time_minutes": 35,
        "cost_chf": 6.0,
        "calories": 580,
        "protein": 38,
        "carbs": 52,
        "fat": 20,
        "vegetarian": False,
        "vegan": False,
        "gluten_free": True,
        "dairy_free": True,
        "difficulty": "Medium",
        "description": "Warming and fragrant — one of the world's most beloved dishes.",
        "lat": 20.6,
        "lon": 78.9,
        "steps": [
            "Fry onion, garlic, and ginger until soft.",
            "Add curry powder and stir for 1 minute.",
            "Add chicken pieces and cook until sealed.",
            "Pour in tomatoes and coconut milk.",
            "Simmer for 20 minutes until chicken is cooked.",
            "Serve with steamed rice."
        ]
    },
    {
        "id": 5,
        "name": "Greek Salad",
        "country": "Greece",
        "category": "Meal",
        "ingredients": ["tomatoes", "cucumber", "red onion", "olives", "feta", "olive oil", "oregano"],
        "time_minutes": 10,
        "cost_chf": 3.0,
        "calories": 280,
        "protein": 10,
        "carbs": 15,
        "fat": 22,
        "vegetarian": True,
        "vegan": False,
        "gluten_free": True,
        "dairy_free": False,
        "difficulty": "Easy",
        "description": "Fresh, healthy, and zero cooking required. Perfect for busy days.",
        "lat": 39.1,
        "lon": 21.8,
        "steps": [
            "Chop tomatoes, cucumber, and red onion into chunks.",
            "Add olives and crumbled feta cheese.",
            "Drizzle with olive oil.",
            "Sprinkle oregano and a pinch of salt.",
            "Toss gently and serve."
        ]
    },
    {
        "id": 6,
        "name": "Shakshuka",
        "country": "Israel",
        "category": "Meal",
        "ingredients": ["eggs", "tomatoes", "onion", "bell pepper", "garlic", "cumin", "paprika", "bread"],
        "time_minutes": 25,
        "cost_chf": 3.5,
        "calories": 350,
        "protein": 18,
        "carbs": 30,
        "fat": 16,
        "vegetarian": True,
        "vegan": False,
        "gluten_free": False,
        "dairy_free": True,
        "difficulty": "Easy",
        "description": "Eggs poached in spiced tomato sauce — great for breakfast or dinner.",
        "lat": 31.0,
        "lon": 34.9,
        "steps": [
            "Sauté onion and bell pepper until soft.",
            "Add garlic, cumin, and paprika — stir for 1 min.",
            "Pour in crushed tomatoes; simmer 10 minutes.",
            "Make small wells and crack eggs in.",
            "Cover and cook until eggs are just set.",
            "Serve with bread to scoop it up."
        ]
    },
    {
        "id": 7,
        "name": "Fried Rice",
        "country": "China",
        "category": "Meal",
        "ingredients": ["rice", "eggs", "peas", "carrots", "soy sauce", "garlic", "spring onions"],
        "time_minutes": 20,
        "cost_chf": 2.5,
        "calories": 450,
        "protein": 14,
        "carbs": 70,
        "fat": 12,
        "vegetarian": True,
        "vegan": False,
        "gluten_free": False,
        "dairy_free": True,
        "difficulty": "Easy",
        "description": "The perfect way to use leftover rice — fast, cheap, and tasty.",
        "lat": 35.9,
        "lon": 104.2,
        "steps": [
            "Use day-old cold rice for best results.",
            "Stir-fry garlic in oil for 30 seconds.",
            "Add vegetables and cook 2 minutes.",
            "Push veggies aside and scramble eggs.",
            "Add rice and soy sauce, stir everything together.",
            "Top with spring onions and serve."
        ]
    },
    {
        "id": 8,
        "name": "Red Lentil Soup",
        "country": "Turkey",
        "category": "Meal",
        "ingredients": ["red lentils", "onion", "garlic", "tomato paste", "cumin", "paprika", "lemon", "bread"],
        "time_minutes": 30,
        "cost_chf": 2.0,
        "calories": 320,
        "protein": 18,
        "carbs": 52,
        "fat": 4,
        "vegetarian": True,
        "vegan": True,
        "gluten_free": True,
        "dairy_free": True,
        "difficulty": "Easy",
        "description": "Cheap, filling, healthy — arguably the best value meal in the world.",
        "lat": 38.9,
        "lon": 35.2,
        "steps": [
            "Sauté onion and garlic until golden.",
            "Add tomato paste, cumin, paprika — stir 1 min.",
            "Add lentils and 1L water; bring to boil.",
            "Simmer 20 minutes until lentils are soft.",
            "Blend until smooth (or leave chunky).",
            "Squeeze lemon on top and serve with bread."
        ]
    },
    {
        "id": 9,
        "name": "Crêpes",
        "country": "France",
        "category": ["Snack","Meal", "Dessert"],
        "ingredients": ["flour", "eggs", "milk", "butter", "sugar", "vanilla", "jam or nutella"],
        "time_minutes": 20,
        "cost_chf": 2.5,
        "calories": 380,
        "protein": 10,
        "carbs": 58,
        "fat": 12,
        "vegetarian": True,
        "vegan": False,
        "gluten_free": False,
        "dairy_free": False,
        "difficulty": "Easy",
        "description": "Light, thin French pancakes — perfect for a sweet breakfast or snack.",
        "lat": 46.2,
        "lon": 2.2,
        "steps": [
            "Whisk flour, eggs, milk, and melted butter into a smooth batter.",
            "Let batter rest 10 minutes.",
            "Heat a pan on medium with a tiny bit of butter.",
            "Pour a ladle of batter and tilt pan to spread thin.",
            "Cook 1-2 min each side until golden.",
            "Fill with jam, Nutella, or fresh fruit."
        ]
    },
    {
        "id": 10,
        "name": "Jollof Rice",
        "country": "Nigeria",
        "category": "Meal",
        "ingredients": ["rice", "tomatoes", "onion", "bell pepper", "garlic", "chicken", "paprika", "stock"],
        "time_minutes": 45,
        "cost_chf": 5.5,
        "calories": 560,
        "protein": 32,
        "carbs": 72,
        "fat": 14,
        "vegetarian": False,
        "vegan": False,
        "gluten_free": True,
        "dairy_free": True,
        "difficulty": "Medium",
        "description": "West Africa's most celebrated dish — smoky, spiced, one-pot perfection.",
        "lat": 9.1,
        "lon": 8.7,
        "steps": [
            "Blend tomatoes, onion, and bell pepper into a puree.",
            "Fry chicken pieces until browned; set aside.",
            "Fry garlic in the same pot, then add tomato puree.",
            "Cook puree down for 10 min until darkened.",
            "Add rice, stock, and paprika; stir well.",
            "Cover and cook on low 25 min until rice is done."
        ]
    },
    {
        "id": 11,
        "name": "Rösti",
        "country": "Switzerland",
        "category": "Meal",
        "ingredients": ["potatoes", "butter", "salt", "black pepper", "egg (optional)"],
        "time_minutes": 30,
        "cost_chf": 2.0,
        "calories": 350,
        "protein": 7,
        "carbs": 58,
        "fat": 12,
        "vegetarian": True,
        "vegan": False,
        "gluten_free": True,
        "dairy_free": False,
        "difficulty": "Easy",
        "description": "Switzerland's iconic crispy potato cake — simple and incredibly delicious.",
        "lat": 46.8,
        "lon": 8.2,
        "steps": [
            "Grate raw potatoes and squeeze out excess water.",
            "Season with salt and pepper.",
            "Melt butter in a pan on medium heat.",
            "Add potato and press into a flat cake.",
            "Cook 10-12 min on each side until golden and crispy.",
            "Serve with sour cream or a fried egg on top."
        ]
    },
    {
        "id": 12,
        "name": "Falafel Wrap",
        "country": "Lebanon",
        "category": "Meal",
        "ingredients": ["canned chickpeas", "garlic", "cumin", "coriander", "flour", "pita bread", "yogurt", "salad"],
        "time_minutes": 25,
        "cost_chf": 3.5,
        "calories": 480,
        "protein": 20,
        "carbs": 62,
        "fat": 16,
        "vegetarian": True,
        "vegan": False,
        "gluten_free": False,
        "dairy_free": False,
        "difficulty": "Medium",
        "description": "Crispy chickpea fritters in a pita — fresh, filling, and full of flavour.",
        "lat": 33.9,
        "lon": 35.5,
        "steps": [
            "Blend chickpeas, garlic, cumin, coriander, and flour.",
            "Shape mixture into small balls or patties.",
            "Fry in oil for 3-4 min until deep golden.",
            "Warm pita bread in a pan.",
            "Fill with falafel, salad, and yogurt sauce.",
            "Roll up and enjoy."
        ]
    },
    {
        "id": 13,
        "name": "Avocado Toast",
        "country": "Australia",
        "category": ["Snack", "Meal"],
        "ingredients": ["bread", "avocado", "lemon", "salt", "chili flakes", "eggs"],
        "time_minutes": 10,
        "cost_chf": 3.0,
        "calories": 380,
        "protein": 14,
        "carbs": 35,
        "fat": 22,
        "vegetarian": True,
        "vegan": False,
        "gluten_free": False,
        "dairy_free": True,
        "difficulty": "Easy",
        "description": "The iconic millennial breakfast — but actually nutritious and quick.",
        "lat": -25.3,
        "lon": 133.8,
        "steps": [
            "Toast bread until golden.",
            "Mash avocado with lemon juice and salt.",
            "Spread avocado generously on toast.",
            "Fry or poach an egg.",
            "Place egg on top, add chili flakes.",
            "Serve immediately."
        ]
    },
    {
        "id": 14,
        "name": "Vegetable Paella",
        "country": "Spain",
        "category": "Meal",
        "ingredients": ["paella rice", "bell peppers", "tomatoes", "onion", "garlic", "paprika", "saffron", "vegetable stock"],
        "time_minutes": 40,
        "cost_chf": 5.0,
        "calories": 490,
        "protein": 12,
        "carbs": 85,
        "fat": 8,
        "vegetarian": True,
        "vegan": True,
        "gluten_free": True,
        "dairy_free": True,
        "difficulty": "Medium",
        "description": "Spain's most famous dish in a vegetarian version — colourful and aromatic.",
        "lat": 40.5,
        "lon": -3.7,
        "steps": [
            "Sauté onion, garlic, and peppers in olive oil.",
            "Add paprika and saffron; stir 1 minute.",
            "Add rice and toast for 1 minute.",
            "Pour in stock, add tomatoes; do not stir again.",
            "Cook on medium 20 min until rice absorbs liquid.",
            "Let rest 5 min before serving."
        ]
    },
    {
        "id": 15,
        "name": "Miso Soup with Rice",
        "country": "Japan",
        "category": "Meal",
        "ingredients": ["rice", "miso paste", "tofu", "seaweed", "spring onions", "soy sauce"],
        "time_minutes": 15,
        "cost_chf": 3.0,
        "calories": 310,
        "protein": 14,
        "carbs": 50,
        "fat": 6,
        "vegetarian": True,
        "vegan": True,
        "gluten_free": False,
        "dairy_free": True,
        "difficulty": "Easy",
        "description": "A light, nourishing Japanese meal — comforting and quick to prepare.",
        "lat": 36.2,
        "lon": 138.3,
        "steps": [
            "Cook rice according to package instructions.",
            "Heat 500ml water — do NOT boil.",
            "Dissolve miso paste in a little water, then add to pot.",
            "Add cubed tofu and seaweed.",
            "Simmer gently 3 min — do not boil.",
            "Serve soup alongside rice, topped with spring onions."
        ]
    },
    {
        "id": 16,
        "name": "Mujaddara",
        "country": "Lebanon",
        "category": "Meal",
        "ingredients": ["lentils", "rice", "onion", "olive oil", "cumin", "coriander", "salt"],
        "time_minutes": 35,
        "cost_chf": 2.0,
        "calories": 400,
        "protein": 16,
        "carbs": 70,
        "fat": 8,
        "vegetarian": True,
        "vegan": True,
        "gluten_free": True,
        "dairy_free": True,
        "difficulty": "Easy",
        "description": "Ancient Middle Eastern lentils and rice with crispy onions. Budget champion.",
        "lat": 33.9,
        "lon": 35.5,
        "steps": [
            "Boil lentils in water for 15 min until soft.",
            "Slice onions thinly and fry in olive oil until very dark and crispy.",
            "Add rice to lentils with cumin, coriander, and salt.",
            "Cook another 15 min until rice is done.",
            "Top with crispy onions and serve."
        ]
    },
    {
        "id": 17,
        "name": "Bean & Cheese Burrito",
        "country": "Mexico",
        "category": "Meal",
        "ingredients": ["large tortillas", "canned black beans", "cheddar cheese", "rice", "sour cream", "salsa"],
        "time_minutes": 15,
        "cost_chf": 3.5,
        "calories": 550,
        "protein": 24,
        "carbs": 72,
        "fat": 16,
        "vegetarian": True,
        "vegan": False,
        "gluten_free": False,
        "dairy_free": False,
        "difficulty": "Easy",
        "description": "Filling, cheap, and endlessly customisable. A student meal legend.",
        "lat": 23.6,
        "lon": -102.5,
        "steps": [
            "Warm beans in a pan, season with salt and cumin.",
            "Cook rice if needed.",
            "Warm tortilla in a dry pan.",
            "Layer rice, beans, cheese, and salsa in the centre.",
            "Fold sides in, then roll into a burrito.",
            "Serve with sour cream."
        ]
    },
    {
        "id": 18,
        "name": "Overnight Oats",
        "country": "Sweden",
        "category": ["Breakfast", "Meal", "Snack"],
        "ingredients": ["oats", "milk", "yogurt", "banana", "honey", "berries"],
        "time_minutes": 5,
        "cost_chf": 1.5,
        "calories": 380,
        "protein": 14,
        "carbs": 65,
        "fat": 8,
        "vegetarian": True,
        "vegan": False,
        "gluten_free": False,
        "dairy_free": False,
        "difficulty": "Easy",
        "description": "Prepare in 5 min the night before. Wake up to a healthy, ready breakfast.",
        "lat": 60.1,
        "lon": 18.6,
        "steps": [
            "Add oats, milk, and yogurt to a jar or bowl.",
            "Slice banana and add on top.",
            "Drizzle honey and add berries.",
            "Stir gently, cover, and refrigerate overnight.",
            "Grab and eat straight from the fridge in the morning."
        ]
    },
    {
        "id": 19,
        "name": "Pierogi (Potato Dumplings)",
        "country": "Poland",
        "category": "Meal",
        "ingredients": ["flour", "eggs", "butter", "potatoes", "cheddar cheese", "onion", "sour cream"],
        "time_minutes": 50,
        "cost_chf": 4.0,
        "calories": 520,
        "protein": 16,
        "carbs": 78,
        "fat": 18,
        "vegetarian": True,
        "vegan": False,
        "gluten_free": False,
        "dairy_free": False,
        "difficulty": "Medium",
        "description": "Polish stuffed dumplings — a labour of love that feeds a whole group.",
        "lat": 51.9,
        "lon": 19.1,
        "steps": [
            "Make dough: mix flour, eggs, water, and a pinch of salt.",
            "Boil potatoes until soft, then mash with cheese and fried onion.",
            "Roll dough thin and cut into circles.",
            "Place a spoon of filling on each circle, fold and seal edges.",
            "Boil in salted water 3-4 min until they float.",
            "Fry in butter until golden. Serve with sour cream."
        ]
    },
    {
        "id": 20,
        "name": "Pho-style Noodle Soup",
        "country": "Vietnam",
        "category": "Meal",
        "ingredients": ["rice noodles", "vegetable stock", "ginger", "soy sauce", "tofu", "bean sprouts", "lime", "spring onions"],
        "time_minutes": 25,
        "cost_chf": 4.0,
        "calories": 360,
        "protein": 16,
        "carbs": 58,
        "fat": 6,
        "vegetarian": True,
        "vegan": True,
        "gluten_free": True,
        "dairy_free": True,
        "difficulty": "Easy",
        "description": "A warming Vietnamese noodle soup — light yet deeply satisfying.",
        "lat": 14.1,
        "lon": 108.3,
        "steps": [
            "Simmer stock with ginger and soy sauce for 10 min.",
            "Cook rice noodles separately, then drain.",
            "Pan-fry tofu until golden.",
            "Place noodles in a bowl, pour hot broth over.",
            "Top with tofu, bean sprouts, and spring onions.",
            "Squeeze lime on top before eating."
        ]
    },
]
