"""
Helpers for Streamlit's session memory (st.session_state).
Defines every key used across the app in one place, initialises them on
page load, and restores the user session after a browser refresh.

Dependencies:

  - streamlit : st.session_state, st.query_params — Streamlit's in-memory store
                and URL parameter access.
  - json      : decodes the wishlist ingredients list stored as a JSON string
                in the database.

  - src.data.user_repo
      load_profile(user_id) -> reloads the user profile from the database
                               when the session is restored after a refresh.

  - src.data.database
      query_df(sql, params) -> used to reload the wishlist from the database
                               on a fresh session.

Authors: Alec Frémond, Giulia De Angelis, Camilla Piano, Ines Buzel

Sources: Claude Sonnet 4.6 (see comments below)

"""

import json

import streamlit as st


#1. Session defaults ################
# DEFAULTS defines every key we want in session_state and its starting value.
# Adding new keys here is safer than scattering checks across every page.

DEFAULTS = {
    "user_id":        None,   # integer primary key from the users table — None means not logged in
    "user_profile":   None,   # dict like {"name": ..., "diet": ...} — filled after login
    "pantry":         [],     # list of dicts: {"name":..., "quantity":..., "unit":..., "expires_on":...}
    "meal_plan":      {},     # dict mapping date string ("2026-04-21") to a list of meal names
    "cooking_history":[],     # list of dicts: {"recipe_id":..., "cooked_on":..., "rating":...}
    "wishlist":       [],     # list of recipe dicts the user saved
}


#2. Session initialisation ##########
# Fills in missing keys, then restores the user session from the URL if the browser was refreshed.

def init_session_state():
    """
    Fills in the DEFAULTS for any keys that are missing from st.session_state.
    Safe to call from every page — only adds keys that don't exist yet,
    so it never overwrites data the user has already entered.

    Also restores the user session after a browser refresh by reading the
    uid query parameter from the URL and reloading the profile and wishlist
    from the database.
    """
    # set all missing keys to their default values
    for key, default in DEFAULTS.items():
        if key not in st.session_state:
            # copy lists/dicts so each session gets its own independent object
            st.session_state[key] = _copy_default(default)

    # \ Begin code generated by Claude Sonnet 4.6
    # When the user refreshes the browser, Streamlit wipes session_state
    # but the URL still contains ?uid=... which we added at login.
    # We read that uid back and restore the session automatically.
    if st.session_state.get("user_id") is None:
        try:
            uid_str = st.query_params.get("uid")
            if uid_str:
                st.session_state["user_id"] = int(uid_str)
        except Exception:
            pass

    # if we recovered a user_id but the profile isn't loaded yet, fetch it from the database
    if st.session_state.get("user_profile") is None and st.session_state.get("user_id") is not None:
        try:
            from src.data.user_repo import load_profile
            saved = load_profile(st.session_state["user_id"])
            if saved is not None:
                st.session_state["user_profile"] = saved
        except Exception:
            pass

    # Streamlit drops query params when the user navigates to a different page.
    # We re-set uid here so it is always present in the URL, enabling persistence on refresh.
    user_id = st.session_state.get("user_id")
    try:
        if user_id is not None:
            if st.query_params.get("uid") != str(user_id):
                st.query_params["uid"] = user_id
        else:
            if "uid" in st.query_params:
                st.query_params.clear()
    except Exception:
        pass

    # If the user opens a new browser tab, session_state is empty.
    # We reload the wishlist from the database so saved recipes are always there.
    if not st.session_state.get("wishlist"):
        try:
            from src.data.database import query_df
            if user_id:
                df = query_df(
                    "SELECT title, image, area, local_id, ingredients "
                    "FROM wishlist WHERE user_id = ?",
                    (user_id,),
                )
                if df is not None and not df.empty:
                    loaded = []
                    for _, row in df.iterrows():
                        try:
                            # ingredients are stored as a JSON string in the database
                            ingredients = json.loads(row["ingredients"] or "[]")
                        except Exception:
                            ingredients = []
                        loaded.append({
                            "title":       row["title"],
                            "image":       row["image"],
                            "area":        row["area"],
                            "local_id":    row["local_id"],
                            "ingredients": ingredients,
                        })
                    st.session_state["wishlist"] = loaded
        except Exception:
            pass
    # \ End code generated by Claude Sonnet 4.6


#3. Profile guard ####
# Stops the page from rendering if the user has not completed onboarding yet.

def require_profile():
    """
    Stops the page and shows a warning if the user hasn't logged in yet.
    Call this at the top of any page that needs a user profile.

    Returns the profile dictionary if it exists.
    """
    init_session_state()

    profile = st.session_state.get("user_profile")

    if not profile:
        st.warning(
            "Please complete **Onboarding** first so we can personalise this page."
        )
        # st.stop() prevents the rest of the page from running — avoids crashes
        st.stop()

    return profile


#4. Helpers ##
# Utility functions used internally by init_session_state.

def _copy_default(value):
    """
    Returns a shallow copy of lists and dicts so each session gets its own object.
    For simple values (None, strings, numbers) returns the value directly.

    Parameters:
        value : any — the default value to copy.
    """
    if isinstance(value, dict):
        return dict(value)
    if isinstance(value, list):
        return list(value)
    return value
