
-- CookTogether database schema.
-- Edit this file to add tables/columns. init_db() in src/data/database.py runs it on app start.
-- All statements are idempotent (IF NOT EXISTS) so reloading is safe.
--
-- Tables:
--   recipes            : catalogue of recipes (from TheMealDB API or user-created).
--   ingredients        : master list of ingredient names (used for pantry matching).
--   recipe_ingredients : junction table linking recipes to their ingredients.
--   users              : one row per registered user (name, diet, login credentials).
--   cooking_history    : log of which recipe each user cooked and when.
--   pantry             : ingredients the user currently has at home, with expiry dates.
--   meal_plan          : which recipe is planned for which meal slot on which day.
--   planner_pool       : staging area used by the Meal Planner page.
--   wishlist           : recipes the user saved with the heart button.
--   user_recipes       : recipes created by users themselves (not from an API).
--   follows            : social graph — who follows whom.
--
-- Authors: Alec Frémond (recipes, ingredients, recipe_ingredients, users, cooking_history),
--          Giulia De Angelis (pantry, meal_plan, planner_pool),
--          Ines buzel (wishlist, user_recipes, follows),
--          Camilla Piano
--
-- Sources: Claude Sonnet 4.6 (see comments below)


--1. Recipe catalogue ################
-- Stores every recipe the app knows about, whether fetched from
-- TheMealDB, Spoonacular, or added manually by a user.
-- mealdb_id links back to the external API so we can fetch fresh
-- data without storing everything locally.

CREATE TABLE IF NOT EXISTS recipes (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    title           TEXT    NOT NULL,
    cuisine         TEXT,           -- e.g. "Italian", "Thai" — used by World Map
    country_iso     TEXT,           -- ISO-3 code for the map layer
    minutes         INTEGER,        -- total prep + cook time
    servings        INTEGER,
    kcal_per_serv   REAL,
    protein_g       REAL,
    carbs_g         REAL,
    fat_g           REAL,
    cost_chf        REAL,           -- estimated cost per serving in CHF
    instructions    TEXT,
    image_url       TEXT,
    source_url      TEXT,           -- where the recipe came from (API or manual)
    mealdb_id       TEXT,           -- TheMealDB idMeal (e.g. '52772'), NULL for Spoonacular
-- \ Begin code generated by Claude Sonnet 4.6
    difficulty      TEXT CHECK(difficulty IN ('easy','medium','hard')),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- \ End code generated by Claude Sonnet 4.6
);


--2. Ingredients and recipe–ingredient links ################
-- ingredients holds the master list of ingredient names.
-- UNIQUE on name prevents duplicates — every pantry entry and
-- recipe ingredient points to a row in this table.
-- recipe_ingredients is the junction table that records which
-- ingredients appear in which recipe, with quantity and unit.

CREATE TABLE IF NOT EXISTS ingredients (
    id      INTEGER PRIMARY KEY AUTOINCREMENT,
    name    TEXT UNIQUE NOT NULL,
    category TEXT                   -- e.g. "vegetable", "dairy", "grain"
);

CREATE TABLE IF NOT EXISTS recipe_ingredients (
    recipe_id     INTEGER NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    ingredient_id INTEGER NOT NULL REFERENCES ingredients(id) ON DELETE CASCADE,
    quantity      REAL,
    unit          TEXT,
    PRIMARY KEY (recipe_id, ingredient_id)
);


--3. Users ################
-- One row per registered user. username and password_hash were
-- added later to support multi-user login (originally the app
-- only stored a name and dietary preferences).
-- allergies is stored as a comma-separated string because SQLite
-- has no array type — the Python layer splits and joins it.

CREATE TABLE IF NOT EXISTS users (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    name          TEXT NOT NULL,
    username      TEXT UNIQUE,
    password_hash TEXT,
    diet          TEXT,
    allergies     TEXT,
    budget_weekly REAL,
-- \ Begin code generated by Claude Sonnet 4.6
    skill_level   TEXT CHECK(skill_level IN ('beginner','intermediate','advanced')),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- \ End code generated by Claude Sonnet 4.6
);


--4. Cooking history ################
-- Records every time a user marks a recipe as cooked.
-- rating (1–5) is optional — NULL means the user didn't rate it.
-- The index on user_id speeds up loading the history for a given
-- user without scanning the whole table.

CREATE TABLE IF NOT EXISTS cooking_history (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id    INTEGER REFERENCES users(id) ON DELETE CASCADE,
    recipe_id  INTEGER REFERENCES recipes(id) ON DELETE CASCADE,
    cooked_on  DATE    NOT NULL,
-- \ Begin code generated by Claude Sonnet 4.6
    rating     INTEGER CHECK(rating BETWEEN 1 AND 5)
-- \ End code generated by Claude Sonnet 4.6
);

-- \ Begin code generated by Claude Sonnet 4.6
CREATE INDEX IF NOT EXISTS idx_recipes_cuisine ON recipes(cuisine);
CREATE INDEX IF NOT EXISTS idx_history_user   ON cooking_history(user_id);
-- \ End code generated by Claude Sonnet 4.6


--5. Pantry ################
-- Stores ingredients the user currently has at home.
-- Used by 3_Pantry.py (manage stock) and the Recipes page
-- (compute the Pantry-friendly badge).
-- UNIQUE (user_id, ingredient_id) means adding the same ingredient
-- twice updates the existing row instead of creating a duplicate.

CREATE TABLE IF NOT EXISTS pantry (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id       INTEGER NOT NULL REFERENCES users(id)       ON DELETE CASCADE,
    ingredient_id INTEGER NOT NULL REFERENCES ingredients(id) ON DELETE CASCADE,
    quantity      REAL    NOT NULL DEFAULT 0,
    unit          TEXT,
    expires_on    DATE,
    UNIQUE (user_id, ingredient_id)   -- one row per ingredient per user
);

CREATE INDEX IF NOT EXISTS idx_pantry_user ON pantry (user_id);


--6. Meal plan ################
-- One row = one planned meal (e.g. user 1, Monday 2026-05-05, Lunch, recipe 42).
-- meal_date is stored as a text string "YYYY-MM-DD" because SQLite
-- has no native DATE type — the Python layer parses it back to a date object.
-- UNIQUE (user_id, meal_date, meal_type) means each slot holds only one recipe;
-- INSERT OR REPLACE in the Python code swaps it out cleanly.

CREATE TABLE IF NOT EXISTS meal_plan (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id     INTEGER NOT NULL REFERENCES users(id)    ON DELETE CASCADE,
    meal_date   TEXT    NOT NULL,          -- stored as "YYYY-MM-DD"
    meal_type   TEXT    NOT NULL
                    CHECK(meal_type IN ('Breakfast','Lunch','Dinner','Snacks')),
    recipe_id   INTEGER NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    UNIQUE (user_id, meal_date, meal_type)
);

CREATE INDEX IF NOT EXISTS idx_meal_plan_user_date ON meal_plan (user_id, meal_date);


--7. Planner pool ################
-- Staging area for recipes the user wants to consider for the meal plan.
-- Recipes are added here from the Recipes page before being assigned
-- to a specific day and meal slot in meal_plan.

CREATE TABLE IF NOT EXISTS planner_pool (
    id        INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id   INTEGER,
    recipe_id INTEGER,
    title     TEXT,
    meal_type TEXT
);


--8. Wishlist ################
-- Recipes the user saved with the heart button on the Recipes page.
-- We store title, image, area and the ingredient list as a JSON string
-- so the page can rebuild each card without an extra API call.
-- local_id links to recipes.id when we have the recipe in our own
-- catalogue; NULL for results that only exist in the external API.
-- UNIQUE (user_id, title) prevents saving the same recipe twice.

CREATE TABLE IF NOT EXISTS wishlist (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title       TEXT    NOT NULL,
    image       TEXT,               -- thumbnail URL (can be NULL for local recipes)
    area        TEXT,               -- cuisine area e.g. "Italian"
    local_id    INTEGER,            -- links to recipes.id if we have it, else NULL
    ingredients TEXT,               -- JSON array of ingredient strings
    UNIQUE (user_id, title)         -- one entry per recipe per user
);


--9. User-created recipes ################
-- Recipes written by users themselves (not pulled from any API).
-- image_data is stored as a base64-encoded string so the app
-- doesn't need a separate file system — the image lives in the database.
-- ingredients and instructions are plain text; the page formats them for display.

CREATE TABLE IF NOT EXISTS user_recipes (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title        TEXT    NOT NULL,
    ingredients  TEXT,               -- plain text, one ingredient per line
    instructions TEXT,               -- step-by-step cooking instructions
    image_data   TEXT,               -- base64-encoded image bytes (can be NULL)
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_recipes_user ON user_recipes (user_id);


--10. Social graph (follows) ################
-- Records who follows whom.
-- follower_id is the user who clicked "Follow",
-- followed_id is the user they are following.
-- status is 'pending' until the followed user accepts, then 'accepted'.
-- UNIQUE (follower_id, followed_id) prevents following the same person twice.

CREATE TABLE IF NOT EXISTS follows (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    follower_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    followed_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status      TEXT    NOT NULL DEFAULT 'pending',
    UNIQUE (follower_id, followed_id)
);
