"""
Streamlit page that renders a weekly meal-planning grid.
Users can assign recipes to specific meal slots (Breakfast, Lunch, Dinner, Snacks) for each day of the week, navigate between weeks, and remove meals.

The `sys.path.append(...)`(line 58) is a workaround so that shared modules living in a sibling 
`src/` folder can be imported without installingthe project as a package.

Dependecies:

  - streamlit          : UI framework; renders every widget, column, and button.
  - pandas             : Handles query results as DataFrames and does lightweight
                         data manipulation (iterrows, set_index).
  - datetime (stdlib)  : date, timedelta — all week-boundary arithmetic.
  - sys, os (stdlib)   : Only used for the path hack at the top.

  - src.data.database
      query_df(sql, params)  -> executes a SELECT and returns a DataFrame
                                (or None if no rows / table missing).
      execute(sql, params)   -> executes INSERT / DELETE / UPDATE statements.

  - src.utils.session
      init_session_state()   -> seeds st.session_state with default keys so
                                the rest of the app never hits KeyError.
      require_profile()      -> redirects to a profile-setup page if the user
                                hasn't created a profile yet.  Acts as a guard.

  - src.components.ui
      page_header(title, subtitle) -> renders a styled h1 + subtitle banner.

Database table:

  meal_plan    : one row per (user, date, meal_type, recipe).
                 Primary key `id` is used for targeted deletes.
  recipes      : master recipe catalogue; joined for human-readable titles.
  planner_pool : a per-user allow-list of recipes that the user has
                 "pinned" to their planner.  Only these appear in dropdowns.

Author: Giulia De Angelis

Sources: Claude Sonnet 4.6 (see comments below)

"""

import streamlit as st
from datetime import date, timedelta
import sys
import os
import pandas as pd

#page configuration
sys.path.append(os.path.join(os.path.dirname(__file__), ".."))

from src.data.database import query_df, execute
from src.utils.session import init_session_state, require_profile
from src.components.ui import page_header

st.set_page_config(page_title="Meal Planner", page_icon="📅", layout="wide")
init_session_state()

#constants
DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
MEALS = ["Breakfast", "Lunch", "Dinner", "Snacks"]

def load_meals_for_week(user_id: int, week_start: date, week_end: date):
    """ 
    Takes all planned meals for a given user within a date range (a week)
    Joins meal_plan with recipes so callers get the recipe title directly in one single query
    so we get back both the planned slot and the recipe name, without needing a second query.

    parameters:
                user_id: int -  the logged-in user's database ID.
                week_start: date  — Monday of the displayed week.
                week_end   : date  — Sunday of the displayed week (week_start + 6 days).

    Returns a table (DataFrame) of results. If no meals are planned yet, returns an empty table 
    instead of nothing — so the rest of the code never crashes trying to read it.
    """
    
    query = """
        SELECT mp.id, mp.meal_date, mp.meal_type, mp.recipe_id, r.title
        FROM meal_plan mp
        JOIN recipes r ON mp.recipe_id = r.id
        WHERE mp.user_id = ?
        AND mp.meal_date BETWEEN ? AND ?
        ORDER BY mp.meal_date, mp.meal_type
    """
    # dates are stored as ISO strings in SQLite ("YYYY-MM-DD")
    meals_df = query_df(query,(user_id, week_start.isoformat(), week_end.isoformat()))

# \ Begin code generated by Claude Sonnet 4.6
# If the database returns no results, query_df returns None instead of an empty table.
# Calling .iterrows() on None would crash immediately, so we replace it with an empty DataFrame
# — same column structure, zero rows. This ensures the rest of the code  always has something it can safely read.
    if meals_df is None:
        meals_df = pd.DataFrame(columns=["id", "meal_date", "meal_type", "recipe_id", "title"])
    return meals_df
# \ End code generated by Claude Sonnet 4.6

## WEEK START 

# On first load, default the displayed week to the current Monday.
if "week_start" not in st.session_state:
    today = date.today()
    st.session_state.week_start = today - timedelta(days=today.weekday())

#week_current = the Monday of today's real-world week.
week_current = date.today() - timedelta(days=date.today().weekday())
week_start = st.session_state.week_start
week_end = week_start + timedelta(days=6)
week_id = week_start.isoformat()

# \ begin code generated with the help of Claude Sonnet 4.6
##  WEEK NAVIGATION CLEANUP
# Every dropdown on screen writes its own name into Streamlit's memory (session_state) so   
  #Streamlit can track it. When you navigate to a different week, the new week's 
  #dropdowns have different names — but the old week's names are still in the memory. 
  #Streamlit sees names in memory that don't match anything on screen and crashes.

# This fix: before drawing the new week, wipe all names that start with "meal_" from memory. 
# That prefix belongs exclusively to dropdowns in this grid, so deleting them is safe.

if st.session_state.get("active_week") != week_id:
    keys_to_delete = [
        k for k in list(st.session_state.keys())
        if isinstance(k, str) and k.startswith("meal_")]

    for k in keys_to_delete:
        del st.session_state[k]
    st.session_state.active_week = week_id

#\ end code generated with the help of Claude Sonnet 4.6

# Redirects to profile setup if the user has not completed onboarding yet.
require_profile()
page_header("📅 Meal Planner", "Choose your meals in the recipe page and plan your week")


## LOAD MEALS
# Takes all planned meals for the currently displayed week
meals_df = load_meals_for_week(
    user_id=st.session_state.user_id,
    week_start=week_start,
    week_end=week_end
)

## RECIPE DROPDOWN, only load from planner_pool, NOT from the full recipes table.
# Recipes are loaded from the planner_pool, the user's personal chosen list of recipes.
# Meaning that each dropdown shows what the user has "added to meal plan" from the Recipe page
# Removing a recipe from the Recipe page also removes it the dropdown

recipes_df = query_df(
    """
    SELECT pp.recipe_id AS id, r.title
    FROM planner_pool pp
    JOIN recipes r ON pp.recipe_id = r.id
    WHERE pp.user_id = ?
    ORDER BY r.title
    """,
    (st.session_state.user_id,))

if recipes_df is None:
    recipes_df = pd.DataFrame(columns=["id", "title"])

# It converts the recipes table into a simple ID 
# ID to name lookup so the grid can find any recipe title instantly by its ID number.
recipe_dict = recipes_df.set_index("id")["title"].to_dict()

#\ begin code generated with the help of Claude Sonnet 4.6
## PLAN
# This lets each cell check instantly whehter a mela is planned or not. 
# Faster than filtering a DataFrame on every cell, and searching through the full meals table 28 times.
plan = {}
for _, row in meals_df.iterrows():
    d = pd.to_datetime(row["meal_date"]).date().isoformat()
    plan[(d, row["meal_type"])] = row
#\ end code generated with the help of Claude Sonnet 4.6


## WEEK NAVIGATION
# Three-column layout: [<- Prev] [date range ] [Next ->]
c1, c2, c3 = st.columns([1, 2, 1])

with c1:
    if st.button("← Prev week"):
        st.session_state.week_start = week_start - timedelta(days=7)
        st.rerun()

with c2:
    # Show the range in a human-readable way 
    st.markdown(f"### {week_start.strftime('%b %d')} – {week_end.strftime('%b %d, %Y')}")

with c3:
    # Disable "Next week" when the displayed week IS the current week.
    disable_next = week_start >= week_current
    if st.button("Next week →", disabled=disable_next):
        if not disable_next:
            st.session_state.week_start = week_start + timedelta(days=7)
            st.rerun()

st.divider()

## MEAL GRID
st.subheader("Your Week")

cols = st.columns(8) # col 0 = meal-type label; cols 1-7 = Mon-Sun
cols[0].write("")    # blank top-left cell

for i in range(7):
    d = week_start + timedelta(days=i)
    cols[i + 1].markdown(f"**{DAYS[i]}**  \n{d.strftime('%d %b')}")

st.divider()

icons = {
    "Breakfast": "🍳",
    "Lunch": "🥗",
    "Dinner": "🍝",
    "Snacks": "🍰"   }

# One row per meal type (Breakfast, Lunch, Dinner, Snacks)
for meal in MEALS:
    row = st.columns(8)
    row[0].markdown(f"**{meal}**")

    # One cell per day of the week
    for i in range(7):
        d = week_start + timedelta(days=i)
        key = (d.isoformat(), meal)

        with row[i + 1]:
            
            # CASE A: a meal has already been planned for this slot
            if key in plan:
                meal_data = plan[key]
                # Show the meal title with its emoji icon.
                st.markdown(f"{icons.get(meal, '🍽')} **{meal_data['title']}**")

                if st.button("✕", key=f"del_{meal_data['id']}"):
                    execute(
                        "DELETE FROM meal_plan WHERE id = ? AND user_id = ?",
                        (meal_data["id"], st.session_state.user_id)
                    )
                    st.rerun()

            # CASE B: Slot is empty and show a recipe picker dropdown
            else:
                if not recipe_dict:
                    # The user has not added any recipes to their planner pool yet. 
                    #Show a hint
                    st.caption("No recipes saved yet. Go to Recipes to add some!")
                else:
                    select_key = f"meal_{week_id}_{meal}_{d.isoformat()}_{i}"

                    #\ Begin code generated with the help of Claude Sonnet 4.6
                    ## SENTINEL PATTERN
                    # Streamlit renders an unwanted (x) clear button on the
                    # selectbox when the selected value is None.
                    # Fix: use an empty string "" as the "nothing selected"
                    # sentinel instead of None, then map it to "Select..." text
                    # via format_func.  This is a known Streamlit workaround.
                    PLACEHOLDER = ""
                    options = [PLACEHOLDER] + list(recipe_dict.keys())

                    # Convert the sentinel back to None for the check below.
                    selected_raw = st.selectbox(
                        " ",
                        options=options,
                        format_func=lambda x: "Select..." if x == PLACEHOLDER else recipe_dict.get(x, x),
                        key=select_key,
                        label_visibility="collapsed" )

                    selected = selected_raw if selected_raw != PLACEHOLDER else None
                    #\ end code generated with the help of Claude Sonnet 4.6
                    
                    # Only write to the database when the user picked a real recipe.
                    if selected:
                        execute(
                            """
                            INSERT OR REPLACE INTO meal_plan
                            (user_id, meal_date, meal_type, recipe_id)
                            VALUES (?, ?, ?, ?)
                            """,
                            (
                                st.session_state.user_id,
                                d.isoformat(),
                                meal,
                                selected
                            ))
                        st.rerun()

st.divider()
