"""
Data access layer for user accounts and profiles.
Handles account creation, login verification, profile read/write and deletion.
Every function that touches a specific profile takes an explicit user_id so that
pantry and meal-plan data (which already carry user_id foreign keys) stays
properly scoped per person.

Dependencies:

  - hashlib (stdlib)  : SHA-256 password hashing — passwords are never stored in plain text.
  - typing (stdlib)   : Optional — type hints.

  - src.data.database
      query_df(sql, params) -> executes a SELECT and returns a DataFrame
                               (or None if no rows / table missing).
      execute(sql, params)  -> executes INSERT / DELETE / UPDATE statements.

Database tables:

  users : one row per user. Stores name, username, hashed password, diet,
          allergies (comma-separated string), and skill level.
          Primary key `id` is used as foreign key in pantry and meal_plan tables.

Author: Alec Frémond

Sources: Claude Sonnet 4.6 (see comments below)

"""

from __future__ import annotations

import hashlib
from typing import Optional

from src.data.database import execute, query_df


_PROFILE_KEYS = ("name", "diet", "allergies", "budget_weekly", "skill_level")


#1. Password hashing ################
# Passwords are never stored in plain text — only their SHA-256 hash is saved.
# Even if the database is exposed, nobody can recover the original passwords.

# \ Begin code generated by Claude Sonnet 4.6
def _hash(password: str) -> str:
    """
    Returns the SHA-256 hash of a password as a hex string.
    Used both when creating an account and when verifying login credentials —
    the stored hash is compared to the hash of the password the user types in.

    Parameters:
        password : str — the plain-text password to hash.

    Returns a 64-character hex string.
    """
    return hashlib.sha256(password.encode()).hexdigest()
# \ End code generated by Claude Sonnet 4.6


#2. Account management ##########
# Functions to create accounts and verify login credentials.

# \ Begin code generated by Claude Sonnet 4.6
def create_account(profile: dict, username: str, password: str) -> int:
    """
    Creates a new user row in the database and returns the new user_id.
    Raises ValueError if the username is already taken (enforced by UNIQUE index).

    Parameters:
        profile  : dict — contains name, diet, allergies, skill_level.
        username : str  — the chosen username (will be lowercased).
        password : str  — the plain-text password (will be hashed before storage).

    Returns the integer id of the newly created row.
    """
    username = username.strip().lower()

    # check if the username already exists before trying to insert
    taken = query_df("SELECT id FROM users WHERE username = ?", (username,))
    if not taken.empty:
        raise ValueError("This username is already taken.")

    # SQLite doesn't support Python lists — allergies must be serialized to a
    # comma-separated string for storage, then parsed back to a list when loading.
    # e.g. ["Gluten", "Nuts"] → "gluten,nuts" on save, "gluten,nuts" → ["Gluten", "Nuts"] on load
    allergies = profile.get("allergies", [])
    allergies_str = ",".join(allergies) if isinstance(allergies, list) else str(allergies or "")

    execute(
        "INSERT INTO users (name, username, password_hash, diet, allergies, skill_level) "
        "VALUES (?, ?, ?, ?, ?, ?)",
        (
            profile.get("name", ""),
            username,
            _hash(password),
            profile.get("diet", "omnivore"),
            allergies_str,
            profile.get("skill_level", "beginner"),
        ),
    )
    # retrieve the id of the row we just inserted
    df = query_df("SELECT id FROM users WHERE username = ?", (username,))
    return int(df.iloc[0]["id"])


def check_login(username: str, password: str) -> Optional[int]:
    """
    Verifies login credentials by hashing the given password and comparing
    it to the stored hash.

    Parameters:
        username : str — the username entered by the user.
        password : str — the plain-text password entered by the user.

    Returns the user_id if credentials match, or None if they don't.
    """
    df = query_df(
        "SELECT id FROM users WHERE username = ? AND password_hash = ?",
        (username.strip().lower(), _hash(password)),
    )
    return int(df.iloc[0]["id"]) if not df.empty else None
# \ End code generated by Claude Sonnet 4.6


#3. Profile read / write ####
# Functions to save and load the user's profile (diet, allergies, skill level).

def save_profile(profile: dict, user_id: Optional[int] = None) -> int:
    """
    Persists a user profile and returns its database id.
    If user_id is given, updates that row. If None, inserts a new one.

    Parameters:
        profile : dict          — contains name, diet, allergies, skill_level.
        user_id : int or None   — if given, updates that row; if None, inserts a new one.

    Returns the integer id of the saved row.
    """
    # same allergies serialization as in create_account — list to comma-separated string
    allergies = profile.get("allergies", [])
    if isinstance(allergies, list):
        allergies_str = ",".join(allergies)
    else:
        allergies_str = str(allergies or "")

    values = (
        profile.get("name", ""),
        profile.get("diet", "omnivore"),
        allergies_str,
        profile.get("skill_level", "beginner"),
    )

    if user_id is not None:
        # update the existing row — keeps the same id so all foreign keys stay valid
        execute(
            "UPDATE users "
            "SET name=?, diet=?, allergies=?, skill_level=? "
            "WHERE id=?",
            values + (user_id,),
        )
        return user_id

    # no user_id provided — insert a new row
    execute(
        "INSERT INTO users (name, diet, allergies, skill_level) "
        "VALUES (?, ?, ?, ?)",
        values,
    )
    # retrieve the id of the row we just inserted (last inserted row has the highest id)
    df = query_df("SELECT id FROM users ORDER BY id DESC LIMIT 1")
    return int(df.iloc[0]["id"])


def load_profile(user_id: int) -> Optional[dict]:
    """
    Loads a user's profile from the database by their id.
    Returns a dict matching the shape of st.session_state["user_profile"],
    or None if no user with that id exists.

    Parameters:
        user_id : int — the logged-in user's database ID.
    """
    df = query_df("SELECT * FROM users WHERE id = ?", (user_id,))
    if df.empty:
        return None

    row = df.iloc[0]
    # parse the comma-separated allergies string back into a Python list
    raw_allergies = row["allergies"] or ""
    allergies = [a.strip() for a in raw_allergies.split(",") if a.strip()]

    return {
        "name": row["name"] or "",
        "diet": row["diet"] or "omnivore",
        "allergies": allergies,
        "skill_level": row["skill_level"] or "beginner",
    }


#4. Utility ##
# Helper functions for loading all profiles and deleting an account.

def load_all_profiles() -> list[dict]:
    """
    Returns a list of {id, name} for every user in the database.
    Used to display a profile-selection screen.
    """
    df = query_df("SELECT id, name FROM users ORDER BY id ASC")
    if df.empty:
        return []
    return df.to_dict("records")


def delete_profile(user_id: int) -> None:
    """
    Deletes the user row. SQLite CASCADE automatically removes
    all their pantry items and meal plan entries as well.

    Parameters:
        user_id : int — the id of the user to delete.
    """
    execute("DELETE FROM users WHERE id = ?", (user_id,))
